//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistryEditProgram.MyResourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FirstTabTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FirstTabTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegistryEditProgram.MyResourses.FirstTabTexts", typeof(FirstTabTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить запись в реестр.
        /// </summary>
        public static string AddNewValueToRegistry {
            get {
                return ResourceManager.GetString("AddNewValueToRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить новую программу в автозагрузку.
        /// </summary>
        public static string AddProgramToAutorun {
            get {
                return ResourceManager.GetString("AddProgramToAutorun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Менеджер автозагрузки.
        /// </summary>
        public static string AutoLoadManager {
            get {
                return ResourceManager.GetString("AutoLoadManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run.
        /// </summary>
        public static string AutorunFullPath {
            get {
                return ResourceManager.GetString("AutorunFullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software\Microsoft\Windows\CurrentVersion\Run.
        /// </summary>
        public static string AutorunSubKeyPath {
            get {
                return ResourceManager.GetString("AutorunSubKeyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоматический запуск.
        /// </summary>
        public static string AutorunThisProgram {
            get {
                return ResourceManager.GetString("AutorunThisProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет фона.
        /// </summary>
        public static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найден инсталятор для выбранной программы! (отсутствует UninstallString).
        /// </summary>
        public static string CantFindUninstaller {
            get {
                return ResourceManager.GetString("CantFindUninstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменения сохранены в реестре!.
        /// </summary>
        public static string ChangesDone {
            get {
                return ResourceManager.GetString("ChangesDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы ничего не изменили! (нечего изменять в реестре).
        /// </summary>
        public static string ChangesNotDone {
            get {
                return ResourceManager.GetString("ChangesNotDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Убедитесь что вы ввели корректное число как размер шрифта!.
        /// </summary>
        public static string CheckDataFirst {
            get {
                return ResourceManager.GetString("CheckDataFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройка  DataGrid (сохраняется в реестре):.
        /// </summary>
        public static string DataGridProperties {
            get {
                return ResourceManager.GetString("DataGridProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер шрифта.
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет шрифта.
        /// </summary>
        public static string ForegroundColor {
            get {
                return ResourceManager.GetString("ForegroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получить список установленных программ.
        /// </summary>
        public static string GetAllSubkeys {
            get {
                return ResourceManager.GetString("GetAllSubkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет заголовков.
        /// </summary>
        public static string HeadersColor {
            get {
                return ResourceManager.GetString("HeadersColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установленные компоненты.
        /// </summary>
        public static string InstalledComponents {
            get {
                return ResourceManager.GetString("InstalledComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\.
        /// </summary>
        public static string KeyToUninstall {
            get {
                return ResourceManager.GetString("KeyToUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegC#Test.
        /// </summary>
        public static string MyRegKey {
            get {
                return ResourceManager.GetString("MyRegKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HKEY_CURRENT_USER\RegC#Test.
        /// </summary>
        public static string MyRegKeyFull {
            get {
                return ResourceManager.GetString("MyRegKeyFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название программы.
        /// </summary>
        public static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HKEY_CURRENT_USER\AutorunOff_DZProgram.
        /// </summary>
        public static string RegistryKeyForAutorunOff {
            get {
                return ResourceManager.GetString("RegistryKeyForAutorunOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutorunOff_DZProgram.
        /// </summary>
        public static string RegistryKeyForAutorunOff_SubKey {
            get {
                return ResourceManager.GetString("RegistryKeyForAutorunOff_SubKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить программу из автозагрузки.
        /// </summary>
        public static string RemoveProgramFromAutorun {
            get {
                return ResourceManager.GetString("RemoveProgramFromAutorun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить изменения в реестре.
        /// </summary>
        public static string SaveChangesAutorun {
            get {
                return ResourceManager.GetString("SaveChangesAutorun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить и применить.
        /// </summary>
        public static string SaveInRegistry {
            get {
                return ResourceManager.GetString("SaveInRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выбрана программа для удаления!.
        /// </summary>
        public static string SelectedNothing {
            get {
                return ResourceManager.GetString("SelectedNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить программу.
        /// </summary>
        public static string UninstallProgram {
            get {
                return ResourceManager.GetString("UninstallProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предупреждение.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
