//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalaryGraphicsBuilder.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SalaryGraphicsBuilder.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Info about program.
        /// </summary>
        public static string CaptionAboutProgram {
            get {
                return ResourceManager.GetString("CaptionAboutProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading info about catalog.
        /// </summary>
        public static string ContentStartForLabelInfoForProgressBar {
            get {
                return ResourceManager.GetString("ContentStartForLabelInfoForProgressBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading list of all catalogs from https://jobs.tut.by/....
        /// </summary>
        public static string FirstContentToShowForLabelInfoForProgressBar {
            get {
                return ResourceManager.GetString("FirstContentToShowForLabelInfoForProgressBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось загрузить данные с https://jobs.tut.by/.
        /// </summary>
        public static string MainLoadHtmlError {
            get {
                return ResourceManager.GetString("MainLoadHtmlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Creator: Saroko Igor Viktorovich
        ///Programming language: C#
        ///Type of project: WPF
        ///External libraries: WPF toolkit
        ///Additional technologies:
        ///	Name: XML;
        ///	Use: storing information about salaries.
        /// </summary>
        public static string MessageAboutProgram {
            get {
                return ResourceManager.GetString("MessageAboutProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading is complete!.
        /// </summary>
        public static string MessageBoxLoadingIsComplete {
            get {
                return ResourceManager.GetString("MessageBoxLoadingIsComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ProfessionsAndSalaries.
        /// </summary>
        public static string NameOfFolderForXMLfilesWithProfessionSalaryInfo {
            get {
                return ResourceManager.GetString("NameOfFolderForXMLfilesWithProfessionSalaryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось загрузить данные с.
        /// </summary>
        public static string UsualLoadHtmlError {
            get {
                return ResourceManager.GetString("UsualLoadHtmlError", resourceCulture);
            }
        }
    }
}
