//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAuto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAuto()
        {
            this.TOwner = new HashSet<TOwner>();
        }
    
        public int ID { get; set; }
        public string Marka { get; set; }
        public Nullable<int> V { get; set; }
        public Nullable<double> R { get; set; }
        public string Country { get; set; }
        public string Date { get; set; }
    
        public virtual TMotor TMotor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOwner> TOwner { get; set; }
    }
}
