//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTPclient.MyResourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FTPclient.MyResourses.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось отправить данные на FTP сервер!.
        /// </summary>
        public static string CantAppendFile {
            get {
                return ResourceManager.GetString("CantAppendFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось создать файл GameInfo.txt на FTP сервере!.
        /// </summary>
        public static string CantGetFile {
            get {
                return ResourceManager.GetString("CantGetFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите крестики или нолики:.
        /// </summary>
        public static string Choice {
            get {
                return ResourceManager.GetString("Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные отправлены!.
        /// </summary>
        public static string GameStatusDataWasSend {
            get {
                return ResourceManager.GetString("GameStatusDataWasSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игра не началась.
        /// </summary>
        public static string GameStatusNone {
            get {
                return ResourceManager.GetString("GameStatusNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подождите....
        /// </summary>
        public static string GameStatusWait {
            get {
                return ResourceManager.GetString("GameStatusWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Локальный IP адрес не найден!.
        /// </summary>
        public static string LocalIpNotFound {
            get {
                return ResourceManager.GetString("LocalIpNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игрок.
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игра завершена.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начать новую  игру .
        /// </summary>
        public static string StartGame {
            get {
                return ResourceManager.GetString("StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дождитесь ответного хода противника!.
        /// </summary>
        public static string WaitForAnswerError {
            get {
                return ResourceManager.GetString("WaitForAnswerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ждать хода противника.
        /// </summary>
        public static string WaitForOpponentButton {
            get {
                return ResourceManager.GetString("WaitForOpponentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы проиграли!.
        /// </summary>
        public static string YouLose {
            get {
                return ResourceManager.GetString("YouLose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы должны сначала выбрать крестики или нолики!.
        /// </summary>
        public static string YouMustSelectChar {
            get {
                return ResourceManager.GetString("YouMustSelectChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы победили!.
        /// </summary>
        public static string YouWin {
            get {
                return ResourceManager.GetString("YouWin", resourceCulture);
            }
        }
    }
}
