//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramForBookingWithoutBug.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProgramForBookingWithoutBug.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сервиз для бронирования билетов.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Забронировать билет.
        /// </summary>
        public static string ButtonBookTicket {
            get {
                return ResourceManager.GetString("ButtonBookTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найти поезд.
        /// </summary>
        public static string ButtonFindTrain {
            get {
                return ResourceManager.GetString("ButtonFindTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начните вводить название станции.
        /// </summary>
        public static string ComboBoxInitText {
            get {
                return ResourceManager.GetString("ComboBoxInitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось выполнить операцию поиска, така как вы не указали все необходимые данные!
        ///(Вы должны указать станцию отправления и станцию назначения).
        /// </summary>
        public static string ErrorNotEnoughData {
            get {
                return ResourceManager.GetString("ErrorNotEnoughData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не можете делать несколько запросов одновременно!
        ///(Дождитесь результата обработки текущего запроса).
        /// </summary>
        public static string ErrorProgramBusy {
            get {
                return ResourceManager.GetString("ErrorProgramBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество не забронированных билетов:.
        /// </summary>
        public static string LabelAmountOfFreeTicketsText {
            get {
                return ResourceManager.GetString("LabelAmountOfFreeTicketsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поезд найден!.
        /// </summary>
        public static string LabelProgramStateReady {
            get {
                return ResourceManager.GetString("LabelProgramStateReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск подходящего поезда....
        /// </summary>
        public static string LabelProgramStateSearch {
            get {
                return ResourceManager.GetString("LabelProgramStateSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не найден подходящий поезд!.
        /// </summary>
        public static string LabelProgramStateTrainNotFound {
            get {
                return ResourceManager.GetString("LabelProgramStateTrainNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите станцию отправления:.
        /// </summary>
        public static string LabelSelectDepartureStation {
            get {
                return ResourceManager.GetString("LabelSelectDepartureStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите станцию назначения:.
        /// </summary>
        public static string LabelSelectDestinationStation {
            get {
                return ResourceManager.GetString("LabelSelectDestinationStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на не выбран маршрут!.
        /// </summary>
        public static string LabelsForValuesErrorText {
            get {
                return ResourceManager.GetString("LabelsForValuesErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Станция не найдена!.
        /// </summary>
        public static string LabelsStationNotFound {
            get {
                return ResourceManager.GetString("LabelsStationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поезд:.
        /// </summary>
        public static string LabelTrainText {
            get {
                return ResourceManager.GetString("LabelTrainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уведомление.
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы забронировали 1 билет на поезд.
        /// </summary>
        public static string NotificationBookingReady {
            get {
                return ResourceManager.GetString("NotificationBookingReady", resourceCulture);
            }
        }
    }
}
