//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatWithoutServer.MyResourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChatWithoutServer.MyResourses.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить новый IP..
        /// </summary>
        public static string AddNewIP {
            get {
                return ResourceManager.GetString("AddNewIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уже добавили этот IP в список!.
        /// </summary>
        public static string CantAddCurrentIP {
            get {
                return ResourceManager.GetString("CantAddCurrentIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось найти маску подсети для локального IP!.
        /// </summary>
        public static string CantFindSubNetMask {
            get {
                return ResourceManager.GetString("CantFindSubNetMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверно введен новый IP адрес!.
        /// </summary>
        public static string CantParseIP {
            get {
                return ResourceManager.GetString("CantParseIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщения чата.
        /// </summary>
        public static string ChatMessages {
            get {
                return ResourceManager.GetString("ChatMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введены недопустимые параметры!.
        /// </summary>
        public static string CheckEnteredParametres {
            get {
                return ResourceManager.GetString("CheckEnteredParametres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клиент уже запущен!.
        /// </summary>
        public static string ClientAlreadyRunning {
            get {
                return ResourceManager.GetString("ClientAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клиент для чата без сервера (UDP).
        /// </summary>
        public static string ClientHeader {
            get {
                return ResourceManager.GetString("ClientHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя клиента:.
        /// </summary>
        public static string ClientName {
            get {
                return ResourceManager.GetString("ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтобы отправить сообщение необходимо указать имя клиента!.
        /// </summary>
        public static string ClientNameError {
            get {
                return ResourceManager.GetString("ClientNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не можете послать сообщение, так как клиент еще не запущен!.
        /// </summary>
        public static string ClinentNotWorkingYet {
            get {
                return ResourceManager.GetString("ClinentNotWorkingYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 239.0.0.222.
        /// </summary>
        public static string DefaultMulticastIP {
            get {
                return ResourceManager.GetString("DefaultMulticastIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8001.
        /// </summary>
        public static string DefaultReceivingPort {
            get {
                return ResourceManager.GetString("DefaultReceivingPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8000.
        /// </summary>
        public static string DefaultSendingPort {
            get {
                return ResourceManager.GetString("DefaultSendingPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно запустить клиент, так как не найден локальный IP!.
        /// </summary>
        public static string LocalIpNotFound {
            get {
                return ResourceManager.GetString("LocalIpNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно запустить клиент! Причина: невозможно установить IP  для массовой рассылки, так как  длина IP адреса и маски подсети не совпадают..
        /// </summary>
        public static string MaskAndIPnotMatch {
            get {
                return ResourceManager.GetString("MaskAndIPnotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP для рассылки:.
        /// </summary>
        public static string MulticastIP {
            get {
                return ResourceManager.GetString("MulticastIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отключен.
        /// </summary>
        public static string NotWorking {
            get {
                return ResourceManager.GetString("NotWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отключить.
        /// </summary>
        public static string OffClient {
            get {
                return ResourceManager.GetString("OffClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст сообщения.
        /// </summary>
        public static string PlaceForMessage {
            get {
                return ResourceManager.GetString("PlaceForMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Порт для отправления сообщений:.
        /// </summary>
        public static string PortForSending {
            get {
                return ResourceManager.GetString("PortForSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Порт для получения сообщений:.
        /// </summary>
        public static string PortListener {
            get {
                return ResourceManager.GetString("PortListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить сообщение.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запустить.
        /// </summary>
        public static string StartClient {
            get {
                return ResourceManager.GetString("StartClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Состояние:.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список IP для рассылки сообщений..
        /// </summary>
        public static string ThisIsBroadcastGroup {
            get {
                return ResourceManager.GetString("ThisIsBroadcastGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Работает.
        /// </summary>
        public static string Working {
            get {
                return ResourceManager.GetString("Working", resourceCulture);
            }
        }
    }
}
