//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace first_test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class main_strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal main_strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("first_test.main_strings", typeof(main_strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to не все поля заполнены!.
        /// </summary>
        internal static string fields_error {
            get {
                return ResourceManager.GetString("fields_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to привет тебе пользователь.
        /// </summary>
        internal static string hi_user_string {
            get {
                return ResourceManager.GetString("hi_user_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to отметки.
        /// </summary>
        internal static string marks_string {
            get {
                return ResourceManager.GetString("marks_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !!!НЕТ ЗАРЕГИСТРИРОВАННЫХ ПОЛЬЗОВАТЕЛЕЙ!!!.
        /// </summary>
        internal static string no_users_string {
            get {
                return ResourceManager.GetString("no_users_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пароль правильный.
        /// </summary>
        internal static string password_accepted_string {
            get {
                return ResourceManager.GetString("password_accepted_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to неверный логин или пароль.
        /// </summary>
        internal static string password_not_accepted_string {
            get {
                return ResourceManager.GetString("password_not_accepted_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтобы просмотреть список занятий вы должны сначала выбрать группу и предмет..
        /// </summary>
        internal static string show_lessons_error {
            get {
                return ResourceManager.GetString("show_lessons_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ученики.
        /// </summary>
        internal static string students_string {
            get {
                return ResourceManager.GetString("students_string", resourceCulture);
            }
        }
    }
}
