//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramForDownloadingWebSites.MyResourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProgramForDownloadingWebSites.MyResourses.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Программа не может выполнить загрузку прямо сейчас, так как она сейчас загружает другой сайт!.
        /// </summary>
        public static string ErrorProgramBusy {
            get {
                return ResourceManager.GetString("ErrorProgramBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .html.
        /// </summary>
        public static string html {
            get {
                return ResourceManager.GetString("html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Программа для скачивания сайтов..
        /// </summary>
        public static string ProgramTitle {
            get {
                return ResourceManager.GetString("ProgramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сайт уже был загружен!.
        /// </summary>
        public static string SiteAlreadyWasDownload {
            get {
                return ResourceManager.GetString("SiteAlreadyWasDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начать  загрузку сайта.
        /// </summary>
        public static string StartDownload {
            get {
                return ResourceManager.GetString("StartDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Состояние:.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идет скачивание сайта!.
        /// </summary>
        public static string StatusBusy {
            get {
                return ResourceManager.GetString("StatusBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to бездействие....
        /// </summary>
        public static string StatusFree {
            get {
                return ResourceManager.GetString("StatusFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите URL сайта для скачивания:.
        /// </summary>
        public static string URLtext {
            get {
                return ResourceManager.GetString("URLtext", resourceCulture);
            }
        }
    }
}
