//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailSimpleClientProgram.MyResourses {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmailSimpleClientProgram.MyResourses.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить вложение.
        /// </summary>
        public static string AddNewAttachment {
            get {
                return ResourceManager.GetString("AddNewAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список вложений.
        /// </summary>
        public static string AttachemntsList {
            get {
                return ResourceManager.GetString("AttachemntsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не можете отправлять несколько писем одновременно!.
        /// </summary>
        public static string CantSendTwoEmail {
            get {
                return ResourceManager.GetString("CantSendTwoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес получателя (email):.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SimpleMailSender@mail.ru.
        /// </summary>
        public static string EmailAddressForProgram {
            get {
                return ResourceManager.GetString("EmailAddressForProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес отправителя (email):.
        /// </summary>
        public static string EmailAddressFrom {
            get {
                return ResourceManager.GetString("EmailAddressFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не указали один или более параметров, необходимых для отправки письма!.
        /// </summary>
        public static string ParameterEmptyError {
            get {
                return ResourceManager.GetString("ParameterEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль для аутентификации:.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Почтовый клиент..
        /// </summary>
        public static string ProgramHeader {
            get {
                return ResourceManager.GetString("ProgramHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить список.
        /// </summary>
        public static string RemoveAllAttachmentsButton {
            get {
                return ResourceManager.GetString("RemoveAllAttachmentsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить вложение.
        /// </summary>
        public static string RemoveAttachmentButton {
            get {
                return ResourceManager.GetString("RemoveAttachmentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не выбрали вложение для удаления!.
        /// </summary>
        public static string SelectedNone {
            get {
                return ResourceManager.GetString("SelectedNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправить письмо адресату..
        /// </summary>
        public static string SendMessageButton {
            get {
                return ResourceManager.GetString("SendMessageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SMTP сервер:.
        /// </summary>
        public static string SMTPserverName {
            get {
                return ResourceManager.GetString("SMTPserverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Состояние почтового клиента:.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на пытается отправить сообщение по указанному адресу.....
        /// </summary>
        public static string StatusBusy {
            get {
                return ResourceManager.GetString("StatusBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на бездейтствует....
        /// </summary>
        public static string StatusFree {
            get {
                return ResourceManager.GetString("StatusFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тема сообщения.
        /// </summary>
        public static string SubjectField {
            get {
                return ResourceManager.GetString("SubjectField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле для ввода сообщения.
        /// </summary>
        public static string TextBoxForMessage {
            get {
                return ResourceManager.GetString("TextBoxForMessage", resourceCulture);
            }
        }
    }
}
