//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager_on_wpf.my_resourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskManager_on_wpf.my_resourses.texts", typeof(texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автообновление.
        /// </summary>
        public static string auto_refresh {
            get {
                return ResourceManager.GetString("auto_refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновлять раз в.
        /// </summary>
        public static string auto_refresh_per_value {
            get {
                return ResourceManager.GetString("auto_refresh_per_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не выбрали процесс для завершения!.
        /// </summary>
        public static string bad_selected_index {
            get {
                return ResourceManager.GetString("bad_selected_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Синий.
        /// </summary>
        public static string blue {
            get {
                return ResourceManager.GetString("blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обычный.
        /// </summary>
        public static string default_scene {
            get {
                return ResourceManager.GetString("default_scene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы действительно хотите завершить процесс.
        /// </summary>
        public static string do_you_wish_end_task {
            get {
                return ResourceManager.GetString("do_you_wish_end_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтры:.
        /// </summary>
        public static string filter {
            get {
                return ResourceManager.GetString("filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найти.
        /// </summary>
        public static string find_task {
            get {
                return ResourceManager.GetString("find_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зеленый.
        /// </summary>
        public static string green {
            get {
                return ResourceManager.GetString("green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справка.
        /// </summary>
        public static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данная программа представляет собой простой менеджер процессов, запущенных ОС или пользователем. С помощью этой программы вы можете получить основную информацию о запущенных процессах и их характеристиках. Кроме того вы можете завершать работу текущих процессов и запускать новые..
        /// </summary>
        public static string help_itself {
            get {
                return ResourceManager.GetString("help_itself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kb.
        /// </summary>
        public static string kbyte {
            get {
                return ResourceManager.GetString("kbyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершить процесс.
        /// </summary>
        public static string kill_task {
            get {
                return ResourceManager.GetString("kill_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string main {
            get {
                return ResourceManager.GetString("main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Макс. обьем физической памяти:.
        /// </summary>
        public static string max_physical_memory {
            get {
                return ResourceManager.GetString("max_physical_memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory.
        /// </summary>
        public static string memory {
            get {
                return ResourceManager.GetString("memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый процесс.
        /// </summary>
        public static string new_task {
            get {
                return ResourceManager.GetString("new_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невыгружаемая память:.
        /// </summary>
        public static string nonpaged_memory {
            get {
                return ResourceManager.GetString("nonpaged_memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to не отвечает.
        /// </summary>
        public static string not_responding {
            get {
                return ResourceManager.GetString("not_responding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выгружаемая память:.
        /// </summary>
        public static string paged_memory {
            get {
                return ResourceManager.GetString("paged_memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Макс. объем виртуальной памяти:.
        /// </summary>
        public static string peak_virtual_memory {
            get {
                return ResourceManager.GetString("peak_virtual_memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приоритет:.
        /// </summary>
        public static string priority {
            get {
                return ResourceManager.GetString("priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Красный.
        /// </summary>
        public static string red {
            get {
                return ResourceManager.GetString("red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to работает.
        /// </summary>
        public static string responding {
            get {
                return ResourceManager.GetString("responding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to секунд.
        /// </summary>
        public static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время создания процесса:.
        /// </summary>
        public static string start_time {
            get {
                return ResourceManager.GetString("start_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Состояние:.
        /// </summary>
        public static string state {
            get {
                return ResourceManager.GetString("state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Процесса с таким именем не существует.
        /// </summary>
        public static string task_dont_exist {
            get {
                return ResourceManager.GetString("task_dont_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string task_name {
            get {
                return ResourceManager.GetString("task_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полное время процессора:.
        /// </summary>
        public static string total_processor_time {
            get {
                return ResourceManager.GetString("total_processor_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь.
        /// </summary>
        public static string user_name {
            get {
                return ResourceManager.GetString("user_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользовательское время процессора:.
        /// </summary>
        public static string user_processor_time {
            get {
                return ResourceManager.GetString("user_processor_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид.
        /// </summary>
        public static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предупреждение!.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
    }
}
