//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RaceWebsite.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string ButtonSaveChanges {
            get {
                return ResourceManager.GetString("ButtonSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start  race.
        /// </summary>
        public static string ButtonStartRace {
            get {
                return ResourceManager.GetString("ButtonStartRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More details.
        /// </summary>
        public static string DetailsButton {
            get {
                return ResourceManager.GetString("DetailsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы не поддерживаем Internet Explorer!.
        /// </summary>
        public static string ErrorMessageForIEUsers {
            get {
                return ResourceManager.GetString("ErrorMessageForIEUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main page for admin.
        /// </summary>
        public static string LinkToMainPageForAdmin {
            get {
                return ResourceManager.GetString("LinkToMainPageForAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main page for users.
        /// </summary>
        public static string LinkToMainPageForUsers {
            get {
                return ResourceManager.GetString("LinkToMainPageForUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance covered.
        /// </summary>
        public static string PDistanceCovered {
            get {
                return ResourceManager.GetString("PDistanceCovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance from start to finish (Km).
        /// </summary>
        public static string PEnterFinishDistance {
            get {
                return ResourceManager.GetString("PEnterFinishDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Km.
        /// </summary>
        public static string PKilometers {
            get {
                return ResourceManager.GetString("PKilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save changes!.
        /// </summary>
        public static string PSaveChangesFail {
            get {
                return ResourceManager.GetString("PSaveChangesFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes have been successfully saved!.
        /// </summary>
        public static string PSaveChangesSuccess {
            get {
                return ResourceManager.GetString("PSaveChangesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main page.
        /// </summary>
        public static string RaceWebsiteMainPage {
            get {
                return ResourceManager.GetString("RaceWebsiteMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biography.
        /// </summary>
        public static string SpanBiography {
            get {
                return ResourceManager.GetString("SpanBiography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        public static string SpanCarName {
            get {
                return ResourceManager.GetString("SpanCarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car speed.
        /// </summary>
        public static string SpanCarSpeed {
            get {
                return ResourceManager.GetString("SpanCarSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string SpanColor {
            get {
                return ResourceManager.GetString("SpanColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string SpanFirstName {
            get {
                return ResourceManager.GetString("SpanFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kph.
        /// </summary>
        public static string SpanKph {
            get {
                return ResourceManager.GetString("SpanKph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants.
        /// </summary>
        public static string SpanParticipants {
            get {
                return ResourceManager.GetString("SpanParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The race has already started. You must wait until the end of the current race, to start a new one..
        /// </summary>
        public static string SpanRaceHasAlreadyStartedYouMustWait {
            get {
                return ResourceManager.GetString("SpanRaceHasAlreadyStartedYouMustWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second name.
        /// </summary>
        public static string SpanSecondName {
            get {
                return ResourceManager.GetString("SpanSecondName", resourceCulture);
            }
        }
    }
}
