//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RaceWebsite.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save changes.
        /// </summary>
        public static string ButtonSaveChanges {
            get {
                return ResourceManager.GetString("ButtonSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start  race.
        /// </summary>
        public static string ButtonStartRace {
            get {
                return ResourceManager.GetString("ButtonStartRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на More details.
        /// </summary>
        public static string DetailsButton {
            get {
                return ResourceManager.GetString("DetailsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Distance covered.
        /// </summary>
        public static string PDistanceCovered {
            get {
                return ResourceManager.GetString("PDistanceCovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Distance from start to finish (Km).
        /// </summary>
        public static string PEnterFinishDistance {
            get {
                return ResourceManager.GetString("PEnterFinishDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Km.
        /// </summary>
        public static string PKilometers {
            get {
                return ResourceManager.GetString("PKilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to save changes!.
        /// </summary>
        public static string PSaveChangesFail {
            get {
                return ResourceManager.GetString("PSaveChangesFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Changes have been successfully saved!.
        /// </summary>
        public static string PSaveChangesSuccess {
            get {
                return ResourceManager.GetString("PSaveChangesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Biography.
        /// </summary>
        public static string SpanBiography {
            get {
                return ResourceManager.GetString("SpanBiography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Car.
        /// </summary>
        public static string SpanCarName {
            get {
                return ResourceManager.GetString("SpanCarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Car speed.
        /// </summary>
        public static string SpanCarSpeed {
            get {
                return ResourceManager.GetString("SpanCarSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Color.
        /// </summary>
        public static string SpanColor {
            get {
                return ResourceManager.GetString("SpanColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на First name.
        /// </summary>
        public static string SpanFirstName {
            get {
                return ResourceManager.GetString("SpanFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kph.
        /// </summary>
        public static string SpanKph {
            get {
                return ResourceManager.GetString("SpanKph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Participants.
        /// </summary>
        public static string SpanParticipants {
            get {
                return ResourceManager.GetString("SpanParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The race has already started. You must wait until the end of the current race, to start a new one..
        /// </summary>
        public static string SpanRaceHasAlreadyStartedYouMustWait {
            get {
                return ResourceManager.GetString("SpanRaceHasAlreadyStartedYouMustWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Second name.
        /// </summary>
        public static string SpanSecondName {
            get {
                return ResourceManager.GetString("SpanSecondName", resourceCulture);
            }
        }
    }
}
