//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NewsWebsite.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create news.
        /// </summary>
        public static string ButtonCreateNews {
            get {
                return ResourceManager.GetString("ButtonCreateNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More details.
        /// </summary>
        public static string ButtonDetailsAboutNews {
            get {
                return ResourceManager.GetString("ButtonDetailsAboutNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string ButtonSearch {
            get {
                return ResourceManager.GetString("ButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search news with this header.
        /// </summary>
        public static string ButtonSearchNewsByHeaderText {
            get {
                return ResourceManager.GetString("ButtonSearchNewsByHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body:.
        /// </summary>
        public static string EditorForNews_Body {
            get {
                return ResourceManager.GetString("EditorForNews_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header:.
        /// </summary>
        public static string EditorForNews_Header {
            get {
                return ResourceManager.GetString("EditorForNews_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot news:.
        /// </summary>
        public static string EditorForNews_HotNews {
            get {
                return ResourceManager.GetString("EditorForNews_HotNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News type:.
        /// </summary>
        public static string EditorForNews_NewsType {
            get {
                return ResourceManager.GetString("EditorForNews_NewsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find news in database with the identifier.
        /// </summary>
        public static string ExceptionCantFindNewsWithID {
            get {
                return ResourceManager.GetString("ExceptionCantFindNewsWithID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News object does not contain a property with name .
        /// </summary>
        public static string ExceptionNewsPropertyWithSuchNameDoesNotExist {
            get {
                return ResourceManager.GetString("ExceptionNewsPropertyWithSuchNameDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest news.
        /// </summary>
        public static string HeaderLatestNews {
            get {
                return ResourceManager.GetString("HeaderLatestNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string HeaderNews {
            get {
                return ResourceManager.GetString("HeaderNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News home page.
        /// </summary>
        public static string HeaderNewsHomePage {
            get {
                return ResourceManager.GetString("HeaderNewsHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page is for print.
        /// </summary>
        public static string HeaderPrintVersion {
            get {
                return ResourceManager.GetString("HeaderPrintVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to admin home page.
        /// </summary>
        public static string LinkBackToAdminMainPage {
            get {
                return ResourceManager.GetString("LinkBackToAdminMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to all news.
        /// </summary>
        public static string LinkBackToAllNews {
            get {
                return ResourceManager.GetString("LinkBackToAllNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To home page.
        /// </summary>
        public static string LinkBackToHomePage {
            get {
                return ResourceManager.GetString("LinkBackToHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site home page.
        /// </summary>
        public static string LinkBackToSiteHomePage {
            get {
                return ResourceManager.GetString("LinkBackToSiteHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View this news as usual.
        /// </summary>
        public static string LinkBackToUsualViewFromPrintView {
            get {
                return ResourceManager.GetString("LinkBackToUsualViewFromPrintView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create news.
        /// </summary>
        public static string LinkCreateNews {
            get {
                return ResourceManager.GetString("LinkCreateNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To admin page.
        /// </summary>
        public static string LinkToAdmin {
            get {
                return ResourceManager.GetString("LinkToAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all news.
        /// </summary>
        public static string LinkToAllNews {
            get {
                return ResourceManager.GetString("LinkToAllNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and edit all news.
        /// </summary>
        public static string LinkToAllNewsForAdmin {
            get {
                return ResourceManager.GetString("LinkToAllNewsForAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print version.
        /// </summary>
        public static string LinkToPrintVersion {
            get {
                return ResourceManager.GetString("LinkToPrintVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search news by header:.
        /// </summary>
        public static string ParagraphSearchNewsByHeader {
            get {
                return ResourceManager.GetString("ParagraphSearchNewsByHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search news by type:.
        /// </summary>
        public static string ParagraphSearchNewsByType {
            get {
                return ResourceManager.GetString("ParagraphSearchNewsByType", resourceCulture);
            }
        }
    }
}
