//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NewsWebsite.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create news.
        /// </summary>
        public static string ButtonCreateNews {
            get {
                return ResourceManager.GetString("ButtonCreateNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на More details.
        /// </summary>
        public static string ButtonDetailsAboutNews {
            get {
                return ResourceManager.GetString("ButtonDetailsAboutNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Body:.
        /// </summary>
        public static string EditorForNews_Body {
            get {
                return ResourceManager.GetString("EditorForNews_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Header:.
        /// </summary>
        public static string EditorForNews_Header {
            get {
                return ResourceManager.GetString("EditorForNews_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hot news:.
        /// </summary>
        public static string EditorForNews_HotNews {
            get {
                return ResourceManager.GetString("EditorForNews_HotNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на News type:.
        /// </summary>
        public static string EditorForNews_NewsType {
            get {
                return ResourceManager.GetString("EditorForNews_NewsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to find news in database with the identifier.
        /// </summary>
        public static string ExceptionCantFindNewsWithID {
            get {
                return ResourceManager.GetString("ExceptionCantFindNewsWithID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на News object does not contain a property with name .
        /// </summary>
        public static string ExceptionNewsPropertyWithSuchNameDoesNotExist {
            get {
                return ResourceManager.GetString("ExceptionNewsPropertyWithSuchNameDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Latest news.
        /// </summary>
        public static string HeaderLatestNews {
            get {
                return ResourceManager.GetString("HeaderLatestNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на News.
        /// </summary>
        public static string HeaderNews {
            get {
                return ResourceManager.GetString("HeaderNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на News home page.
        /// </summary>
        public static string HeaderNewsHomePage {
            get {
                return ResourceManager.GetString("HeaderNewsHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This page is for print.
        /// </summary>
        public static string HeaderPrintVersion {
            get {
                return ResourceManager.GetString("HeaderPrintVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back to admin home page.
        /// </summary>
        public static string LinkBackToAdminMainPage {
            get {
                return ResourceManager.GetString("LinkBackToAdminMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back to all news.
        /// </summary>
        public static string LinkBackToAllNews {
            get {
                return ResourceManager.GetString("LinkBackToAllNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To home page.
        /// </summary>
        public static string LinkBackToHomePage {
            get {
                return ResourceManager.GetString("LinkBackToHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Site home page.
        /// </summary>
        public static string LinkBackToSiteHomePage {
            get {
                return ResourceManager.GetString("LinkBackToSiteHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на View this news as usual.
        /// </summary>
        public static string LinkBackToUsualViewFromPrintView {
            get {
                return ResourceManager.GetString("LinkBackToUsualViewFromPrintView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create news.
        /// </summary>
        public static string LinkCreateNews {
            get {
                return ResourceManager.GetString("LinkCreateNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To admin page.
        /// </summary>
        public static string LinkToAdmin {
            get {
                return ResourceManager.GetString("LinkToAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на View all news.
        /// </summary>
        public static string LinkToAllNews {
            get {
                return ResourceManager.GetString("LinkToAllNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на View and edit all news.
        /// </summary>
        public static string LinkToAllNewsForAdmin {
            get {
                return ResourceManager.GetString("LinkToAllNewsForAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Print version.
        /// </summary>
        public static string LinkToPrintVersion {
            get {
                return ResourceManager.GetString("LinkToPrintVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search news by header:.
        /// </summary>
        public static string ParagraphSearchNewsByHeader {
            get {
                return ResourceManager.GetString("ParagraphSearchNewsByHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search news by type:.
        /// </summary>
        public static string ParagraphSearchNewsByType {
            get {
                return ResourceManager.GetString("ParagraphSearchNewsByType", resourceCulture);
            }
        }
    }
}
