//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientForDiskDataProvider.MyResourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClientForDiskDataProvider.MyResourses.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось найти диск  с таким именем.
        /// </summary>
        public static string CantFindDriveByName {
            get {
                return ResourceManager.GetString("CantFindDriveByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клиент для службы возвращающей информацию о диске.
        /// </summary>
        public static string ClientHeader {
            get {
                return ResourceManager.GetString("ClientHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общая информация о всех дисках.
        /// </summary>
        public static string CommonDriversInfo {
            get {
                return ResourceManager.GetString("CommonDriversInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ep_1.
        /// </summary>
        public static string EndPoint_1 {
            get {
                return ResourceManager.GetString("EndPoint_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ep_2.
        /// </summary>
        public static string EndPoint_2 {
            get {
                return ResourceManager.GetString("EndPoint_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to свободно.
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to из.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получить информацию о всех дисках.
        /// </summary>
        public static string GetCommonInfoAboutDriversButton {
            get {
                return ResourceManager.GetString("GetCommonInfoAboutDriversButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получить информацию о всех дисках (асинхронно).
        /// </summary>
        public static string GetCommonInfoAboutDriversButtonAsync {
            get {
                return ResourceManager.GetString("GetCommonInfoAboutDriversButtonAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инфо о диске.
        /// </summary>
        public static string GetDriveInfoButton {
            get {
                return ResourceManager.GetString("GetDriveInfoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получить список дисков.
        /// </summary>
        public static string GetDriversNamesButton {
            get {
                return ResourceManager.GetString("GetDriversNamesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гб.
        /// </summary>
        public static string GigaByte {
            get {
                return ResourceManager.GetString("GigaByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дождитесь окончания обработки предыдущего запроса!.
        /// </summary>
        public static string ProgramBusyError {
            get {
                return ResourceManager.GetString("ProgramBusyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Состояние клиента:.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнение пользовательского запроса к службе....
        /// </summary>
        public static string StatusBusy {
            get {
                return ResourceManager.GetString("StatusBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершение работы клиента....
        /// </summary>
        public static string StatusClosing {
            get {
                return ResourceManager.GetString("StatusClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бездействие....
        /// </summary>
        public static string StatusFree {
            get {
                return ResourceManager.GetString("StatusFree", resourceCulture);
            }
        }
    }
}
