//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOwner
    {
        public int IDO { get; set; }
        public Nullable<int> ID { get; set; }
        public string Fam { get; set; }
        public Nullable<double> Opyt { get; set; }
        public Nullable<int> Garanty { get; set; }
        public string Date { get; set; }
    
        public virtual TAuto TAuto { get; set; }
    }
}
