//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientForWCFchat.MyResourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClientForWCFchat.MyResourses.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сейчас в чате:.
        /// </summary>
        public static string ClientInChatLabel {
            get {
                return ResourceManager.GetString("ClientInChatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя клиента не может быть пустым!.
        /// </summary>
        public static string ClientNameEmptyError {
            get {
                return ResourceManager.GetString("ClientNameEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя клиента:.
        /// </summary>
        public static string ClientNameLabel {
            get {
                return ResourceManager.GetString("ClientNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя вашего клиента уже используется!.
        /// </summary>
        public static string InvalidClientNameError {
            get {
                return ResourceManager.GetString("InvalidClientNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подключиться к чату.
        /// </summary>
        public static string JoinChatButton {
            get {
                return ResourceManager.GetString("JoinChatButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы еще не вошли в чат!.
        /// </summary>
        public static string NotInChatError {
            get {
                return ResourceManager.GetString("NotInChatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Личные сообщения.
        /// </summary>
        public static string PrivateChatLabel {
            get {
                return ResourceManager.GetString("PrivateChatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Личное сообщение.
        /// </summary>
        public static string PrivateMessageTabItem {
            get {
                return ResourceManager.GetString("PrivateMessageTabItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общий чат.
        /// </summary>
        public static string PublicChatLabel {
            get {
                return ResourceManager.GetString("PublicChatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Публичное сообщение.
        /// </summary>
        public static string PublicMessageTabItem {
            get {
                return ResourceManager.GetString("PublicMessageTabItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получатель:.
        /// </summary>
        public static string ReceiverLabel {
            get {
                return ResourceManager.GetString("ReceiverLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не указали имя клиента, который должен получить приватное сообщение!.
        /// </summary>
        public static string ReceiverUnknown {
            get {
                return ResourceManager.GetString("ReceiverUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить сообщение.
        /// </summary>
        public static string SendMessageButton {
            get {
                return ResourceManager.GetString("SendMessageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя дважы подключить один клиент к чату!.
        /// </summary>
        public static string YouAlreadyInChatError {
            get {
                return ResourceManager.GetString("YouAlreadyInChatError", resourceCulture);
            }
        }
    }
}
