//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientSocketTest.MyResourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClientSocketTest.MyResourses.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно послать сообщение, так как отсутствует подключение к серверу!.
        /// </summary>
        public static string CantSendMessage {
            get {
                return ResourceManager.GetString("CantSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось послать сообщение на сервер! (Если проблема не исчезает попробуйте создать подключение заново).
        /// </summary>
        public static string CantSendMessageConnectProblem {
            get {
                return ResourceManager.GetString("CantSendMessageConnectProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось уведомить сервер об отключении данного клиента!.
        /// </summary>
        public static string CantSendOffToServer {
            get {
                return ResourceManager.GetString("CantSendOffToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось корректно получить данные о сервере! Проверьте введенные параметры!.
        /// </summary>
        public static string CheckInfoInTextBoxes {
            get {
                return ResourceManager.GetString("CheckInfoInTextBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клиент.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя клиента:.
        /// </summary>
        public static string ClientName {
            get {
                return ResourceManager.GetString("ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string ClientOff {
            get {
                return ResourceManager.GetString("ClientOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Порт клиента (вход):.
        /// </summary>
        public static string ClientPortNumberListen {
            get {
                return ResourceManager.GetString("ClientPortNumberListen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Соединение с сервером уже было установлено!.
        /// </summary>
        public static string ConnectionAlreadyExists {
            get {
                return ResourceManager.GetString("ConnectionAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось установить соединение с сервером!.
        /// </summary>
        public static string ConnectionFail {
            get {
                return ResourceManager.GetString("ConnectionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не можете прервать соединение с сервером, так как оно еще не установлено!.
        /// </summary>
        public static string ConnectionNotExist {
            get {
                return ResourceManager.GetString("ConnectionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Соединение с сервером отключено пользователем..
        /// </summary>
        public static string ConnectionOffByClient {
            get {
                return ResourceManager.GetString("ConnectionOffByClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Соединение с сервером успешно установлено!.
        /// </summary>
        public static string ConnectionSuccess {
            get {
                return ResourceManager.GetString("ConnectionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Соединиться.
        /// </summary>
        public static string ConnectToServer {
            get {
                return ResourceManager.GetString("ConnectToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсоединиться.
        /// </summary>
        public static string DisconnectFromServer {
            get {
                return ResourceManager.GetString("DisconnectFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP сервера:.
        /// </summary>
        public static string IPofServer {
            get {
                return ResourceManager.GetString("IPofServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найден локальный IP для сокета клиента!.
        /// </summary>
        public static string LocalIpNotFound {
            get {
                return ResourceManager.GetString("LocalIpNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение от:.
        /// </summary>
        public static string MessageFrom {
            get {
                return ResourceManager.GetString("MessageFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщения от сервера.
        /// </summary>
        public static string MessagesFromServer {
            get {
                return ResourceManager.GetString("MessagesFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя клиента получателя:.
        /// </summary>
        public static string MessageTarget {
            get {
                return ResourceManager.GetString("MessageTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение:.
        /// </summary>
        public static string MessageToServer {
            get {
                return ResourceManager.GetString("MessageToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение успешно отправлено..
        /// </summary>
        public static string MessageWasSendToServer {
            get {
                return ResourceManager.GetString("MessageWasSendToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Послать сообщение на сервер.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string ServerOff {
            get {
                return ResourceManager.GetString("ServerOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Порт сервера (выход):.
        /// </summary>
        public static string ServerPortNumber {
            get {
                return ResourceManager.GetString("ServerPortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string ServerReady {
            get {
                return ResourceManager.GetString("ServerReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервер отключился (соединение разорвано).
        /// </summary>
        public static string ServerShutDown {
            get {
                return ResourceManager.GetString("ServerShutDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервер недоступен!.
        /// </summary>
        public static string ServerUnavailable {
            get {
                return ResourceManager.GetString("ServerUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не указали имя клиента получателя!.
        /// </summary>
        public static string TargetUnknown {
            get {
                return ResourceManager.GetString("TargetUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Устанавливается соединение с сервером....
        /// </summary>
        public static string TryingToConnect {
            get {
                return ResourceManager.GetString("TryingToConnect", resourceCulture);
            }
        }
    }
}
