//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanksOnMap.MyResourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BanksOnMap.MyResourses.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить:.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить банк.
        /// </summary>
        public static string AddBank {
            get {
                return ResourceManager.GetString("AddBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить перерыв.
        /// </summary>
        public static string AddBreakTime {
            get {
                return ResourceManager.GetString("AddBreakTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить отзыв:.
        /// </summary>
        public static string AddComment {
            get {
                return ResourceManager.GetString("AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес:.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название банка (обязательно):.
        /// </summary>
        public static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to с.
        /// </summary>
        public static string Begin {
            get {
                return ResourceManager.GetString("Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Координаты выбранного объекта (обязательно):.
        /// </summary>
        public static string BranchCoordinates {
            get {
                return ResourceManager.GetString("BranchCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название отделения (обязательно):.
        /// </summary>
        public static string BranchName {
            get {
                return ResourceManager.GetString("BranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перерывы:.
        /// </summary>
        public static string Breaks {
            get {
                return ResourceManager.GetString("Breaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BreakTimeID.
        /// </summary>
        public static string BreakTimeID {
            get {
                return ResourceManager.GetString("BreakTimeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buy:.
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кассир:.
        /// </summary>
        public static string Cashier {
            get {
                return ResourceManager.GetString("Cashier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон кассира:.
        /// </summary>
        public static string CashierPhone {
            get {
                return ResourceManager.GetString("CashierPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Убедитесь что вы вводили в поля только допустимые значения!.
        /// </summary>
        public static string CheckCharacharsError {
            get {
                return ResourceManager.GetString("CheckCharacharsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Убедитесь, что вы выбрали все параметры для поиска!.
        /// </summary>
        public static string CheckRadioButtonsError {
            get {
                return ResourceManager.GetString("CheckRadioButtonsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommentItself.
        /// </summary>
        public static string CommentItself {
            get {
                return ResourceManager.GetString("CommentItself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отзывы:.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BanksConnectionString.
        /// </summary>
        public static string ConnectionStringName {
            get {
                return ResourceManager.GetString("ConnectionStringName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать новый объект.
        /// </summary>
        public static string CreateNewElement {
            get {
                return ResourceManager.GetString("CreateNewElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить отзыв.
        /// </summary>
        public static string DeleteComment {
            get {
                return ResourceManager.GetString("DeleteComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить услугу.
        /// </summary>
        public static string DeleteService {
            get {
                return ResourceManager.GetString("DeleteService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to до.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка!.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EURO.
        /// </summary>
        public static string EURO {
            get {
                return ResourceManager.GetString("EURO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EURORadioButton.
        /// </summary>
        public static string EURORadioButton {
            get {
                return ResourceManager.GetString("EURORadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курсы валют:.
        /// </summary>
        public static string ExchangeRates {
            get {
                return ResourceManager.GetString("ExchangeRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле для создания комментария:.
        /// </summary>
        public static string FieldForComment {
            get {
                return ResourceManager.GetString("FieldForComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кнопка ниже находит ближайшее 
        ///отделение банка к текущему центру карты 
        ///(Красный крестик на карте).
        /// </summary>
        public static string FindNearestExplanation {
            get {
                return ResourceManager.GetString("FindNearestExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Часы:.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Широта:.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Долгота:.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Координаты центра карты:.
        /// </summary>
        public static string MapCoordinates {
            get {
                return ResourceManager.GetString("MapCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Худшая цена покупки.
        /// </summary>
        public static string MaxBuyValue {
            get {
                return ResourceManager.GetString("MaxBuyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxBuyValueRadioButton.
        /// </summary>
        public static string MaxBuyValueRadioButton {
            get {
                return ResourceManager.GetString("MaxBuyValueRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лучшая цена продажи.
        /// </summary>
        public static string MaxSellValue {
            get {
                return ResourceManager.GetString("MaxSellValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxSellValueRadioButton.
        /// </summary>
        public static string MaxSellValueRadioButton {
            get {
                return ResourceManager.GetString("MaxSellValueRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лучшая цена покупки.
        /// </summary>
        public static string MinBuyValue {
            get {
                return ResourceManager.GetString("MinBuyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinBuyValueRadioButton.
        /// </summary>
        public static string MinBuyValueRadioButton {
            get {
                return ResourceManager.GetString("MinBuyValueRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Худшая цена продажи.
        /// </summary>
        public static string MinSellValue {
            get {
                return ResourceManager.GetString("MinSellValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinSellValueRadioButton.
        /// </summary>
        public static string MinSellValueRadioButton {
            get {
                return ResourceManager.GetString("MinSellValueRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минуты:.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы ничего не выбрали для удаления!.
        /// </summary>
        public static string NoSelectedItems {
            get {
                return ResourceManager.GetString("NoSelectedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон:.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POINT.
        /// </summary>
        public static string POINT {
            get {
                return ResourceManager.GetString("POINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RelatedBranches.
        /// </summary>
        public static string RelatedBranches {
            get {
                return ResourceManager.GetString("RelatedBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить перерыв.
        /// </summary>
        public static string RemoveBreakTime {
            get {
                return ResourceManager.GetString("RemoveBreakTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RUB.
        /// </summary>
        public static string RUB {
            get {
                return ResourceManager.GetString("RUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RUBRadioButton.
        /// </summary>
        public static string RUBRadioButton {
            get {
                return ResourceManager.GetString("RUBRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить изменения.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбранный элемент.
        /// </summary>
        public static string SelectedInfo {
            get {
                return ResourceManager.GetString("SelectedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sell:.
        /// </summary>
        public static string Sell {
            get {
                return ResourceManager.GetString("Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Услуги:.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напишите новую услугу:.
        /// </summary>
        public static string ServicesInDB {
            get {
                return ResourceManager.GetString("ServicesInDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servise.
        /// </summary>
        public static string Servise {
            get {
                return ResourceManager.GetString("Servise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найти.
        /// </summary>
        public static string StartSearch {
            get {
                return ResourceManager.GetString("StartSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD.
        /// </summary>
        public static string USD {
            get {
                return ResourceManager.GetString("USD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USDRadioButton.
        /// </summary>
        public static string USDRadioButton {
            get {
                return ResourceManager.GetString("USDRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Использовать координаты
        ///центра карты вместо 
        ///ручного ввода при изменении
        ///или добавлении объекта..
        /// </summary>
        public static string UseCenterCoordinates {
            get {
                return ResourceManager.GetString("UseCenterCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время работы:.
        /// </summary>
        public static string WorkHours {
            get {
                return ResourceManager.GetString("WorkHours", resourceCulture);
            }
        }
    }
}
