//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rating_system.my_resourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("rating_system.my_resourses.texts", typeof(texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add new.
        /// </summary>
        public static string add_new {
            get {
                return ResourceManager.GetString("add_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 rank assassin.
        /// </summary>
        public static string assassin_rank {
            get {
                return ResourceManager.GetString("assassin_rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssassinId.
        /// </summary>
        public static string assassinId {
            get {
                return ResourceManager.GetString("assassinId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alive.
        /// </summary>
        public static string bad_result {
            get {
                return ResourceManager.GetString("bad_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assassins guild.
        /// </summary>
        public static string campaing_name {
            get {
                return ResourceManager.GetString("campaing_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change.
        /// </summary>
        public static string change {
            get {
                return ResourceManager.GetString("change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change style.
        /// </summary>
        public static string change_style {
            get {
                return ResourceManager.GetString("change_style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description for operation.
        /// </summary>
        public static string description_for_operation {
            get {
                return ResourceManager.GetString("description_for_operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change image.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ratings data.
        /// </summary>
        public static string edit_ratings {
            get {
                return ResourceManager.GetString("edit_ratings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string education {
            get {
                return ResourceManager.GetString("education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empty.
        /// </summary>
        public static string empty {
            get {
                return ResourceManager.GetString("empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assassins guild rating system.
        /// </summary>
        public static string fame_board {
            get {
                return ResourceManager.GetString("fame_board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dead.
        /// </summary>
        public static string good_result {
            get {
                return ResourceManager.GetString("good_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to battle with more than 2 guards.
        /// </summary>
        public static string kill_many_guards {
            get {
                return ResourceManager.GetString("kill_many_guards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kill target with poison.
        /// </summary>
        public static string kill_target_with_poison {
            get {
                return ResourceManager.GetString("kill_target_with_poison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kill target with trap.
        /// </summary>
        public static string kill_target_with_trap {
            get {
                return ResourceManager.GetString("kill_target_with_trap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating for the last 5 years.
        /// </summary>
        public static string last_5_yers_graph {
            get {
                return ResourceManager.GetString("last_5_yers_graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIST OF OPERATIONS:.
        /// </summary>
        public static string list_of_operations {
            get {
                return ResourceManager.GetString("list_of_operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list of styles -&gt;.
        /// </summary>
        public static string list_of_styles {
            get {
                return ResourceManager.GetString("list_of_styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string location {
            get {
                return ResourceManager.GetString("location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to operation name.
        /// </summary>
        public static string operation_name {
            get {
                return ResourceManager.GetString("operation_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string rank {
            get {
                return ResourceManager.GetString("rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rating.
        /// </summary>
        public static string rating {
            get {
                return ResourceManager.GetString("rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rating data for each year.
        /// </summary>
        public static string ratings_data_last_years {
            get {
                return ResourceManager.GetString("ratings_data_last_years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string salary {
            get {
                return ResourceManager.GetString("salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must first select an assassin!.
        /// </summary>
        public static string selected_null {
            get {
                return ResourceManager.GetString("selected_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must first select an image!.
        /// </summary>
        public static string selected_null_picture {
            get {
                return ResourceManager.GetString("selected_null_picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must first select an operation!.
        /// </summary>
        public static string selected_operation_null {
            get {
                return ResourceManager.GetString("selected_operation_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stealth missions.
        /// </summary>
        public static string stealth_orders {
            get {
                return ResourceManager.GetString("stealth_orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to work in team.
        /// </summary>
        public static string work_in_team {
            get {
                return ResourceManager.GetString("work_in_team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year.
        /// </summary>
        public static string year {
            get {
                return ResourceManager.GetString("year", resourceCulture);
            }
        }
    }
}
