//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gas_station {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gas_station.texts", typeof(texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступные услуги:.
        /// </summary>
        internal static string available_services {
            get {
                return ResourceManager.GetString("available_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to купить.
        /// </summary>
        internal static string buy {
            get {
                return ResourceManager.GetString("buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите стиль:.
        /// </summary>
        internal static string choose_your_style {
            get {
                return ResourceManager.GetString("choose_your_style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to очистить.
        /// </summary>
        internal static string clean_up {
            get {
                return ResourceManager.GetString("clean_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка! Введите количество литров бензина для покупки!.
        /// </summary>
        internal static string error_gas {
            get {
                return ResourceManager.GetString("error_gas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка! Введите количество  единиц товара для покупки!.
        /// </summary>
        internal static string error_goods {
            get {
                return ResourceManager.GetString("error_goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to продажи бензина.
        /// </summary>
        internal static string gas_deals {
            get {
                return ResourceManager.GetString("gas_deals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to узнать цену.
        /// </summary>
        internal static string get_price {
            get {
                return ResourceManager.GetString("get_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to продажи товаров.
        /// </summary>
        internal static string goods_deals {
            get {
                return ResourceManager.GetString("goods_deals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сколько единиц товара.
        /// </summary>
        internal static string how_many_goods {
            get {
                return ResourceManager.GetString("how_many_goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to литров..
        /// </summary>
        internal static string of_liter {
            get {
                return ResourceManager.GetString("of_liter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to рублей..
        /// </summary>
        internal static string of_money {
            get {
                return ResourceManager.GetString("of_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to убрать.
        /// </summary>
        internal static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to добавить.
        /// </summary>
        internal static string take {
            get {
                return ResourceManager.GetString("take", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this is test.
        /// </summary>
        internal static string test_string {
            get {
                return ResourceManager.GetString("test_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to вы хотите купить?.
        /// </summary>
        internal static string you_want_buy {
            get {
                return ResourceManager.GetString("you_want_buy", resourceCulture);
            }
        }
    }
}
