//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopyFilesAsync.MyResourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CopyFilesAsync.MyResourses.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BREAK.
        /// </summary>
        public static string BREAK {
            get {
                return ResourceManager.GetString("BREAK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прервано!.
        /// </summary>
        public static string BreakNow {
            get {
                return ResourceManager.GetString("BreakNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбранный сейчас процесс:.
        /// </summary>
        public static string CurrentProcess {
            get {
                return ResourceManager.GetString("CurrentProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл успешно скопирован!.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmptyForever.
        /// </summary>
        public static string EmptyForever {
            get {
                return ResourceManager.GetString("EmptyForever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка!.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПЕРВАЯ МАТРИЦА.
        /// </summary>
        public static string FirstMatrix {
            get {
                return ResourceManager.GetString("FirstMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FROM.
        /// </summary>
        public static string FROM {
            get {
                return ResourceManager.GetString("FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        public static string Full {
            get {
                return ResourceManager.GetString("Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершить выбранный процесс.
        /// </summary>
        public static string KillProcess {
            get {
                return ResourceManager.GetString("KillProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВТОРАЯ МАТРИЦА.
        /// </summary>
        public static string LastMatrix {
            get {
                return ResourceManager.GetString("LastMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список библиотек.
        /// </summary>
        public static string ListOfDlls {
            get {
                return ResourceManager.GetString("ListOfDlls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество столбцов:.
        /// </summary>
        public static string MatrixColumns {
            get {
                return ResourceManager.GetString("MatrixColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Умножение матриц.
        /// </summary>
        public static string MatrixMultiplication {
            get {
                return ResourceManager.GetString("MatrixMultiplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество строк:.
        /// </summary>
        public static string MatrixRows {
            get {
                return ResourceManager.GetString("MatrixRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Матрицы таких размеров нельзя перемножить! Убедитесь, что количество колонок в первой матрице равняется количеству строк во второй..
        /// </summary>
        public static string MultiplicationImpossible {
            get {
                return ResourceManager.GetString("MultiplicationImpossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAUSE.
        /// </summary>
        public static string PAUSE {
            get {
                return ResourceManager.GetString("PAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приостановлено!.
        /// </summary>
        public static string PauseNow {
            get {
                return ResourceManager.GetString("PauseNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Процессы.
        /// </summary>
        public static string Processes {
            get {
                return ResourceManager.GetString("Processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessName.
        /// </summary>
        public static string ProcessName {
            get {
                return ResourceManager.GetString("ProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Программа уже запущена! .
        /// </summary>
        public static string ProgramAlreadyRunning {
            get {
                return ResourceManager.GetString("ProgramAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результирующая матрица.
        /// </summary>
        public static string ResultMatrix {
            get {
                return ResourceManager.GetString("ResultMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START.
        /// </summary>
        public static string START {
            get {
                return ResourceManager.GetString("START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приступить к генерации и умножению матриц..
        /// </summary>
        public static string StartMatrixMultiplication {
            get {
                return ResourceManager.GetString("StartMatrixMultiplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запустить потоки.
        /// </summary>
        public static string StartRrocThreads {
            get {
                return ResourceManager.GetString("StartRrocThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вычислить 40 площадей треугольников.
        /// </summary>
        public static string StartTriangleAreaCalculation {
            get {
                return ResourceManager.GetString("StartTriangleAreaCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список потоков.
        /// </summary>
        public static string ThreadList {
            get {
                return ResourceManager.GetString("ThreadList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поток обновляющий список потоков и библиотек выбранного процесса прекращает свою работу!.
        /// </summary>
        public static string ThreadModulesDllsDied {
            get {
                return ResourceManager.GetString("ThreadModulesDllsDied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поток обновляющий список процессов прекращает свою работу!.
        /// </summary>
        public static string ThreadProcessesDied {
            get {
                return ResourceManager.GetString("ThreadProcessesDied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы ввели слишком большие размеры матриц! (не влазит в инт).
        /// </summary>
        public static string TooBigNumber {
            get {
                return ResourceManager.GetString("TooBigNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Площади 40 треугольников.
        /// </summary>
        public static string TriangleAreaCalculation {
            get {
                return ResourceManager.GetString("TriangleAreaCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNPAUSE.
        /// </summary>
        public static string UNPAUSE {
            get {
                return ResourceManager.GetString("UNPAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHERE.
        /// </summary>
        public static string WHERE {
            get {
                return ResourceManager.GetString("WHERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Работа с файлами.
        /// </summary>
        public static string WorkWithFiles {
            get {
                return ResourceManager.GetString("WorkWithFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Работа с процессами.
        /// </summary>
        public static string WorkWithProcesses {
            get {
                return ResourceManager.GetString("WorkWithProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы должны корректно указать ВСЕ размеры матрицы!.
        /// </summary>
        public static string WrongFormatRowsColumnsMatrix {
            get {
                return ResourceManager.GetString("WrongFormatRowsColumnsMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество строк или колонок у матрицы не может быть равным нулю!.
        /// </summary>
        public static string ZeroError {
            get {
                return ResourceManager.GetString("ZeroError", resourceCulture);
            }
        }
    }
}
