//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FromPythonAndRubyToExcel.MyResources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FromPythonAndRubyToExcel.MyResources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create and save Excel graph (Python).
        /// </summary>
        public static string CreateAndSavePythonButton {
            get {
                return ResourceManager.GetString("CreateAndSavePythonButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create and save Excel graph (Ruby).
        /// </summary>
        public static string CreateAndSaveRubyButton {
            get {
                return ResourceManager.GetString("CreateAndSaveRubyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на \ResultsOfTests.xls.
        /// </summary>
        public static string DefaultFileName {
            get {
                return ResourceManager.GetString("DefaultFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Details:.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Excel file created , you can find the file .
        /// </summary>
        public static string ExcelFileWasCreatedMessage {
            get {
                return ResourceManager.GetString("ExcelFileWasCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Program cant execute method &apos;GetNewLab()&apos; from current script!.
        /// </summary>
        public static string ExecuteMethodError {
            get {
                return ResourceManager.GetString("ExecuteMethodError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .xls.
        /// </summary>
        public static string ExtensionOfExcelFiles {
            get {
                return ResourceManager.GetString("ExtensionOfExcelFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Find Python Lib.
        /// </summary>
        public static string FindPythonLibraryButton {
            get {
                return ResourceManager.GetString("FindPythonLibraryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select script.
        /// </summary>
        public static string FindScriptButton {
            get {
                return ResourceManager.GetString("FindScriptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Folder name:.
        /// </summary>
        public static string FolderName {
            get {
                return ResourceManager.GetString("FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DLR and COM example program.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exception Occured while releasing object.
        /// </summary>
        public static string ReleaseObjectException {
            get {
                return ResourceManager.GetString("ReleaseObjectException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Creation of Excel graph for data generated by Python script:.
        /// </summary>
        public static string SaveDataFromPythonLabel {
            get {
                return ResourceManager.GetString("SaveDataFromPythonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Creation of Excel graph for data generated by Ruby script:.
        /// </summary>
        public static string SaveDataFromRubyLabel {
            get {
                return ResourceManager.GetString("SaveDataFromRubyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Program cant load current script!.
        /// </summary>
        public static string ScriptExecuteError {
            get {
                return ResourceManager.GetString("ScriptExecuteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save as.
        /// </summary>
        public static string SelectSavePathButtons {
            get {
                return ResourceManager.GetString("SelectSavePathButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Specify the folder that contains Python libraries.
        /// </summary>
        public static string SpecifyPythonLibraryFolderCaption {
            get {
                return ResourceManager.GetString("SpecifyPythonLibraryFolderCaption", resourceCulture);
            }
        }
    }
}
